version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build:
      context: kafka
      dockerfile: Dockerfile
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "km4city:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
  k42k:
    build:
      context: .
      args:
        JAR_FILE: daf-replicate-ingestion-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
# TODO Is this actually ignored?
#    command: --spring.kafka.bootstrap-servers="kafka:9092"